export const countries = [{ name: "Colombia", code: "+57", flag: "🇨🇴" }];

export const idTypes = [
  { label: "CC", value: "CC" },
  { label: "CE", value: "CE" },
  { label: "NIT", value: "NIT" },
  { label: "PAS", value: "PAS" },
];

export const COLOMBIA_REGIONS: Record<string, string[]> = {
  Antioquia: [
    "Medellín",
    "Envigado",
    "Itagüí",
    "Bello",
    "Rionegro",
    "Sabaneta",
    "La Estrella",
    "Caldas",
    "Apartadó",
    "Turbo",
  ],
  Atlántico: ["Barranquilla", "Soledad", "Puerto Colombia", "Malambo", "Galapa"],
  "Bogotá D.C.": ["Bogotá D.C."],
  Bolívar: ["Cartagena", "Magangué", "Turbaco"],
  Caldas: [
    "Manizales",
    "Villamaría",
    "Chinchiná",
    "Neira",
    "Palestina",
    "Aguadas",
    "Anserma",
    "Aranzazu",
    "Belalcázar",
    "Filadelfia",
    "La Dorada",
    "La Merced",
    "Manzanares",
    "Marmato",
    "Marquetalia",
    "Marulanda",
    "Norcasia",
    "Pácora",
    "Pensilvania",
    "Riosucio",
    "Risaralda",
    "Salamina",
    "Samaná",
    "San José",
    "Supía",
    "Victoria",
    "Viterbo",
  ],
  Casanare: ["Yopal", "Aguazul", "Villanueva"],
  Cauca: ["Popayán", "Santander de Quilichao", "Puerto Tejada"],
  Cesar: ["Valledupar", "Aguachica", "Codazzi"],
  Córdoba: ["Montería", "Cereté", "Sahagún", "Lorica"],
  Cundinamarca: [
    "Soacha",
    "Chía",
    "Zipaquirá",
    "Facatativá",
    "Fusagasugá",
    "Mosquera",
    "Madrid",
    "Funza",
    "Cajicá",
    "Girardot",
  ],
  Huila: ["Neiva", "Pitalito", "Garzón"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación"],
  Meta: ["Villavicencio", "Acacías", "Granada"],
  Nariño: ["Pasto", "Ipiales", "Tumaco"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Los Patios"],
  Quindío: ["Armenia", "Calarca", "Circasia", "La Tebaida", "Montenegro", "Quimbaya", "Salento"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
  Santander: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
  Tolima: ["Ibagué", "Espinal", "Melgar"],
  "Valle del Cauca": [
    "Cali",
    "Palmira",
    "Buenaventura",
    "Tuluá",
    "Buga",
    "Cartago",
    "Jamundí",
    "Yumbo",
  ],
};
