export const siteConfig = {
  name: "Möiz",
  fullName: "Möiz Bienestar Animal SAS",
  version: "1.0.0",
  url: "https://moizpets.com",
  ogImage: "https://moizpets.com/og-image.jpg",
  description: "Bienestar Natural & Premium para tus Mascotas",
  slogan: "El Cambio Inteligente en Arena para Gatos",
  keywords: [
    "arena para gatos",
    "arena ecológica",
    "maíz",
    "mascotas",
    "bienestar animal",
    "Colombia",
    "sustentable",
  ],
  navMain: [
    { title: "Inicio", href: "/" },
    { title: "Catálogo", href: "/productos" },
    { title: "Comparativa", href: "/info/arena" },
    { title: "Blog", href: "/blog" },
  ],
  footerLinks: {
    empresa: [
      { title: "Nosotros", href: "/sobre-moiz" },
      { title: "Contacto", href: "/contacto" },
    ],
    legal: [
      { title: "Términos y Condiciones", href: "/legal/terminos" },
      { title: "Privacidad", href: "/legal/privacidad" },
    ],
  },
  links: {
    instagram: "https://instagram.com/moizpets",
    whatsapp: "https://wa.me/573218515161",
    whatsappNumber: "573218515161",
    tiktok: "https://tiktok.com/@moiz",
    facebook: "https://facebook.com/moiz",
  },
  content: {
    heroTitle: "Lleva el bienestar",
    heroSubtitle: "a otro nivel",
    heroTagline: "Sustentabilidad y Amor en cada gramo",
    whatsappDefaultMessage: "¡Hola Möiz! Me interesa saber más sobre sus productos premium.",
  },
  ui: {
    addToCart: "Agregar al carrito",
    buyNow: "Comprar ahora",
    outOfStock: "Agotado",
    itemsInCart: "En carrito",
    viewDetails: "Ver detalles",
    searchPlaceholder: "¿Qué busca hoy la mascota de la casa?...",
    showMore: "Ver más",
    newsletterPlaceholder: "Tu email mejor amigo...",
    subscribe: "Suscribirme",
    ingresar: "Ingresar",
    carrito: "Carrito",
    soporte: "Soporte",
    home: "Inicio",
    productos: "Productos",
    catalogo: "Catálogo",
    resenas: "Reseñas",
    rastrear: "Rastrear Pedido",
    preguntas: "Preguntas",
    noProducts: "No encontramos productos",
    noProductsDesc: "Intenta con otros filtros o términos de búsqueda",
    noOrders: "No tienes pedidos aún",
    noFavorites: "Aún no tienes favoritos",
    featuredSelection: "Selección Destacada",
    curiousFact: "Dato curioso",
    needHelp: "¿Necesitas ayuda?",
    whatsappExpert: "Hablar con un experto",
    whatsappReady: "Estamos listos para ayudarte vía WhatsApp.",
    orderTracking: {
      title: "Rastrear mi pedido",
      placeholder: "MZ-1001",
      cta: "Consultar Estado",
    },
    order: {
      subtotal: "Subtotal",
      shipping: "Envío",
      total: "TOTAL",
      free: "Gratis",
      method: "Método de Envío",
      orderNumberLabel: "Pedido #",
      orderLabel: "Orden #",
      noOrders: "No tienes pedidos aún",
      noOrdersDesc: "Cuando realices una compra, aparecerá aquí para que puedas seguirla.",
      goToStore: "Ir a la tienda",
      today: "Hoy",
      local: "Domicilio Hoy",
      national: "Nacional",
      viewMore: "Ver más",
      status: {
        pendiente: "Pendiente",
        pagado: "Pagado",
        enviado: "Enviado",
        entregado: "Entregado",
        cancelado: "Cancelado",
      },
    },
    invoice: {
      title: "Factura de Venta",
      paid: "Pagado",
      customer: "Cliente",
      docDetails: "Detalles del Documento",
      date: "Fecha",
      orderNumber: "Número de Pedido",
      paymentMethod: "Forma de Pago",
      paymentValue: "Electrónico / Efectivo",
      currency: "Moneda",
      product: "Producto",
      description: "Descripción del Producto",
      qty: "Cant.",
      unitPrice: "V. Unitario",
      totalPrice: "V. Total",
      subtotal: "Subtotal",
      discount: "Descuento",
      total: "TOTAL",
      thanks: "¡Gracias por tu compra!",
      generatedBy: "Generado electrónicamente por Möiz",
    },
    profile: {
      personalInfo: "Información Personal",
      personalInfoDesc: "Estos datos se usarán para tus pedidos y contacto.",
      shippingAddress: "Dirección de Envío",
      shippingAddressDesc: "¿A dónde enviamos tus productos Moiz?",
      billingData: "Datos de Facturación",
      billingDataDesc: "Para generar tus recibos y facturas legales.",
      sameAsShipping: "¿Igual que envío?",
      synced: "Sincronizado con Envío",
    },
    related: {
      title: "Completa el",
      titleAccent: "kit",
      subtitle: "Productos que combinan perfecto con tu selección.",
    },
    cart: {
      title: "Tu Carrito",
      empty: "Carrito Vacío",
      summary: "Resumen",
      checkout: "Proceder al pago",
      continueShopping: "Continuar Comprando",
      subscriptionNotice: {
        commitment: "Compromiso mínimo de 3 entregas.",
        noPrepayment: "Pago mensual al recibir o método elegido.",
        cancellation: "Cancelación disponible después del tercer mes.",
      },
      free: "¡Gratis!",
      calculatedByZone: "Calculado por zona",
      products: "Productos",
      activeCoupon: "Cupón Activo",
      removeCoupon: "Quitar cupón",
      apply: "Aplicar",
      unlockShipping: "¡Desbloqueado! 🎉",
      missingForShipping: "Faltan $",
      orderTotal: "Total del pedido",
      clearCart: "Vaciar carrito",
      selectedProducts: "Productos Seleccionados",
    },
    login: {
      title: "¡Holi de nuevo!",
      subtitle: "Bienvenido a la comunidad Möiz.",
      email: "Correo Electrónico",
      password: "Contraseña",
      cta: "Entrar Ahora",
      noAccount: "¿No tienes una cuenta?",
      register: "Regístrate gratis",
      google: "Ingresar con Google",
      back: "Volver al Inicio",
      orContinue: "O continúa con",
    },
    auth: {
      loggingIn: "Iniciando sesión...",
      error: "Error al iniciar sesión",
    },
    newsletter: {
      title: "Únete al Universo Möiz",
      subtitle: "Recibe un 10% de descuento en tu primera compra y noticias exclusivas.",
      success: "¡Ya eres parte!",
      successDesc: "Pronto recibirás nuestras mejores ofertas.",
    },
    badges: {
      new: "Nuevo",
      offer: "Oferta",
      freeShipping: "Envío Gratis",
      express: "Envío Express",
      expressDesc: "Llega en minutos",
      guarantee: "Garantía Moiz",
      guaranteeDesc: "Calidad asegurada",
      organic: "100% Orgánico",
      organicDesc: "Bienestar natural",
      nutrition: "Nutrición Alta",
      nutritionDesc: "Sabor y energía",
      hygiene: "Higiene Total",
      hygieneDesc: "Libre de olores",
      ratingSuffix: "Estrellas",
      happyPetsSuffix: "Mascotas Felices",
      heroCta: "Adquirir ahora",
      heroBadge: "Bienestar premium para tus mejores amigos",
      fastShipping: "Envíos Rápidos",
      fastShippingDesc: "Entregas en tiempo récord para que tu mascota nunca se quede sin lo que necesita.",
      premiumQuality: "Calidad Premium",
      premiumQualityDesc: "Solo seleccionamos productos de la más alta calidad, priorizando ingredientes naturales.",
      expertSupport: "Soporte Experto",
      expertSupportDesc: "Nuestro equipo está listo para asesorarte en la mejor elección para tu mascota.",
    },
    favorites: {
      title: "Aún no tienes favoritos",
      subtitle: "Explora nuestro catálogo y guarda los productos que más te gustan.",
      explore: "Explorar Productos",
      removeSuccess: "Producto eliminado de favoritos",
    },
    categories: {
      title: "Explora por",
      titleAccent: "Categorías",
      subtitle: "El universo de tus mascotas reunido en cajas de sorpresas. Encuentra rápidamente lo indispensable.",
      viewCatalog: "Ver catálogo completo",
    },
    calculator: {
      title: "Impacto Económico",
      heading: "Calcula tu",
      headingAccent: "Ahorro Anual",
      description: "Por ser una arena de alto rendimiento, Möiz dura más y cuida tu bolsillo.",
      question: "¿Cuántos gatos tienes en casa?",
      catLabel: "Mericat",
      catsLabel: "Mericats",
      estimatedSavings: "Ahorro estimado al año",
      traditional: "Tradicional",
      withMoiz: "Con Möiz",
      disclaimer: "*Cálculo promediado basado en el rendimiento superior de aglomeración del maíz frente a la bentonita común.",
      oneCat: "1 Gato",
      moreCats: "+6 Gatos",
    },
    purchase: {
      once: "Compra única",
      onceDesc: "Pedido estándar sin compromiso",
      subscription: "Suscripción Mensual",
      subscriptionDesc: "Recibe cada mes y ahorra tiempo",
      save: "Ahorra 5%",
      price: "Precio",
      before: "Antes",
      termsTitle: "Términos de Suscripción",
      termsCommitment: "La suscripción tiene un compromiso mínimo de 3 meses (3 entregas).",
      termsNoPrepayment: "Pagas cada mes al momento de recibir o mediante el método elegido.",
      termsCancellation: "Podrás cancelar tu suscripción libremente una vez completadas las primeras 3 entregas.",
    },
    comparison: {
      title: "Möiz vs. Arena Tradicional",
      subtitle: "El Cambio Inteligente",
      tagline: "No es solo arena, es una mejora tecnológica para tu hogar y el planeta.",
      moizStandard: "El Estándar Möiz",
      commonSand: "Arena Común",
    },
    faq: {
      title: "Preguntas Frecuentes",
      subtitle: "Resolvemos tus dudas sobre el bienestar de tu mascota",
    },
  },
  messages: {
    addedToCart: "¡Agregado al carrito!",
    addedToFavorites: "¡Agregado a favoritos!",
    removedFromFavorites: "Eliminado de favoritos",
    profileUpdated: "Información personal actualizada",
    addressSaved: "Dirección guardada correctamente",
  },
  stats: {
    rating: "4.9",
    happyPets: "+10,000",
  },
  theme: {
    primary: "var(--moiz-green)",
    accent: "var(--moiz-yellow)",
  },
};

export type SiteConfig = typeof siteConfig;
